# --- BUILDER STAGE ---
FROM node:20-alpine AS builder
WORKDIR /app

RUN apk add --no-cache openssl

# Build-time Args
ARG DATABASE_URL
ARG GTHB_CLIENT_ID
ARG GTHB_CLIENT_SECRET
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG FAKE_STORE_API_URL

# Build-time Env
ENV DATABASE_URL=$DATABASE_URL
ENV GTHB_CLIENT_ID=$GTHB_CLIENT_ID
ENV GTHB_CLIENT_SECRET=$GTHB_CLIENT_SECRET
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL
ENV FAKE_STORE_API_URL=$FAKE_STORE_API_URL

COPY package*.json ./
COPY prisma ./prisma/ 
RUN npm install && npm cache clean --force
RUN npx prisma generate

COPY . .
RUN npm run build

# --- RUNNER STAGE ---
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN apk add --no-cache openssl

RUN npm install -g prisma@7.4.1

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma

# RUNTIME ARGS & ENVS
ARG DATABASE_URL
ARG GTHB_CLIENT_ID
ARG GTHB_CLIENT_SECRET
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG FAKE_STORE_API_URL

ENV DATABASE_URL=$DATABASE_URL
ENV GTHB_CLIENT_ID=$GTHB_CLIENT_ID
ENV GTHB_CLIENT_SECRET=$GTHB_CLIENT_SECRET
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL
ENV FAKE_STORE_API_URL=$FAKE_STORE_API_URL

EXPOSE 3000

CMD ["sh", "-c", "npx prisma db push && node server.js"]